# @package _global_

defaults:
  - ../env: rlbench/take_lid_off_saucepan
  - ../method: act

demos: 50
num_pretrain_steps: 500000
num_train_frames: 0
eval_every_steps: 2000
num_eval_episodes: 10
batch_size: 256
save_snapshot: true
snapshot_every_n: 0

pixels: true
frame_stack: 1

action_repeat: 1
action_sequence: 20
execution_length: 1
temporal_ensemble: true
use_standardization: false  # Demo-based standardization for action space
use_min_max_normalization: true  # Demo-based min-max normalization for action space
min_max_margin: 0.2

update_every_steps: 1

replay:
  nstep: 1


hydra:
  run:
    dir: ./exp_local/pixel_act/rlbench_${env.task_name}_${now:%Y%m%d%H%M%S}
